package component:library1;

interface greeter {
    record greeting {
        text: string,
        times: list<u32>,
    }

    hello-world: func() -> greeting;
}

/// An example world for the component to target.
world example {
    export greeter;
}
